name: Run Gists Tests

on:
  schedule:
    - cron: "0 */3 * * 1-5"
    - cron: "0 */6 * * 1-5"

  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  critical_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "~3.12"

      - name: Build Docker
        run: docker build -t gists-test .

      - name: Run Critical Tests
        env:
          VALID_GIST_TOKEN: ${{ secrets.VALID_GIST_TOKEN }}
          INVALID_GIST_TOKEN: ${{ secrets.INVALID_GIST_TOKEN }}
        run: docker run -e VALID_GIST_TOKEN=${{ secrets.VALID_GIST_TOKEN }} -e INVALID_GIST_TOKEN=${{ secrets.INVALID_GIST_TOKEN }} -e WITHOUT_PERMISSION_GIST_TOKEN=${{ secrets.WITHOUT_PERMISSION_GIST_TOKEN }} gists-test ./run_critical_cases.sh

      - name: Generate Allure Report
        run: docker run gists-test allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report


  medium_priority_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "~3.12"

      - name: Build Docker
        run: docker build -t gists-test .

      - name: Run Medium Priority Tests
        env:
          VALID_GIST_TOKEN: ${{ secrets.VALID_GIST_TOKEN }}
          INVALID_GIST_TOKEN: ${{ secrets.INVALID_GIST_TOKEN }}
        run: docker run -e VALID_GIST_TOKEN=${{ secrets.VALID_GIST_TOKEN }} -e INVALID_GIST_TOKEN=${{ secrets.INVALID_GIST_TOKEN }} -e WITHOUT_PERMISSION_GIST_TOKEN=${{ secrets.WITHOUT_PERMISSION_GIST_TOKEN }} gists-test ./run_medium_priority_tests.sh

      - name: Generate Allure Report
        run: docker run gists-test allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report