name: Run Gists Tests

on:
  schedule:
    - cron: "0 */3 * * 1-5"
    - cron: "0 */6 * * 1-5"

  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_type: [critical, medium]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "~3.12"

      - name: Build Docker
        run: docker build -t gists-test .

      - name: Run Tests
        env:
          VALID_GIST_TOKEN: ${{ secrets.VALID_GIST_TOKEN }}
          INVALID_GIST_TOKEN: ${{ secrets.INVALID_GIST_TOKEN }}
          WITHOUT_PERMISSION_GIST_TOKEN: ${{ secrets.WITHOUT_PERMISSION_GIST_TOKEN }}
        run: |
          if [ "${{ matrix.test_type }}" == "critical" ]; then
            docker run -e VALID_GIST_TOKEN=${{ secrets.VALID_GIST_TOKEN }} \
              -e INVALID_GIST_TOKEN=${{ secrets.INVALID_GIST_TOKEN }} \
              gists-test ./run_critical_cases.sh
          else
            docker run -e VALID_GIST_TOKEN=${{ secrets.VALID_GIST_TOKEN }} \
              -e INVALID_GIST_TOKEN=${{ secrets.INVALID_GIST_TOKEN }} \
              gists-test ./run_medium_priority_tests.sh
          fi

      - name: Generate Allure Report
        run: |
          if [ "${{ matrix.test_type }}" == "critical" ]; then
            docker run gists-test allure generate allure-results --clean -o allure-report-critical
          else
            docker run gists-test allure generate allure-results --clean -o allure-report-medium
          fi

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          publish_dir: ${{ matrix.test_type == 'critical' && 'allure-report-critical' || 'allure-report-medium' }}
          destination_dir: ${{ matrix.test_type }}
