name: Run Gists Tests

on:
  schedule:
    - cron: "0 */3 * * 1-5"
    - cron: "0 */6 * * 1-5"

  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  critical_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "~3.12"

      - name: Build Docker
        run: docker build -t gists-test .

      - name: Run Critical Tests
        env:
          VALID_GIST_TOKEN: ${{ secrets.VALID_GIST_TOKEN }}
          INVALID_GIST_TOKEN: ${{ secrets.INVALID_GIST_TOKEN }}
        run: docker run -e VALID_GIST_TOKEN=${{ secrets.VALID_GIST_TOKEN }} -e INVALID_GIST_TOKEN=${{ secrets.INVALID_GIST_TOKEN }} -e WITHOUT_PERMISSION_GIST_TOKEN=${{ secrets.WITHOUT_PERMISSION_GIST_TOKEN }} gists-test ./run_critical_cases.sh

      - name: Generate Report for Critical Tests
        run: docker run gists-test behave --tags="@priority-High" --tags="~@skip" --junit --outfile=critical-report

      - name: Deploy Critical Test Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports/critical_report.html
          destination_dir: critical-reports

  medium_priority_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "~3.12"

      - name: Build Docker
        run: docker build -t gists-test .

      - name: Run Medium Priority Tests
        env:
          VALID_GIST_TOKEN: ${{ secrets.VALID_GIST_TOKEN }}
          INVALID_GIST_TOKEN: ${{ secrets.INVALID_GIST_TOKEN }}
        run: docker run -e VALID_GIST_TOKEN=${{ secrets.VALID_GIST_TOKEN }} -e INVALID_GIST_TOKEN=${{ secrets.INVALID_GIST_TOKEN }} -e WITHOUT_PERMISSION_GIST_TOKEN=${{ secrets.WITHOUT_PERMISSION_GIST_TOKEN }} gists-test ./run_medium_priority_tests.sh

      - name: Deploy Medium Priority Test Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports/medium_report.html
          destination_dir: medium-reports