name: Run Gists Tests

on:
  schedule:
    - cron: "0 */3 * * 1-5"
    - cron: "0 */6 * * 1-5"

  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_type: [critical, medium]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "~3.12"

      - name: Build Docker
        run: docker build -t gists-test .

      - name: Install Allure CLI
        run: |
          sudo apt-get update && sudo apt-get install -y curl unzip && \
          curl -sLo allure.zip https://github.com/allure-framework/allure2/releases/latest/download/allure-2.22.5.zip && \
          unzip allure.zip -d /tmp/ && sudo mv /tmp/allure-2.22.5 /opt/allure && \
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Run Tests
        env:
          VALID_GIST_TOKEN: ${{ secrets.VALID_GIST_TOKEN }}
          INVALID_GIST_TOKEN: ${{ secrets.INVALID_GIST_TOKEN }}
          WITHOUT_PERMISSION_GIST_TOKEN: ${{ secrets.WITHOUT_PERMISSION_GIST_TOKEN }}
        run: |
          if [ "${{ matrix.test_type }}" == "critical" ]; then
            ./run_critical_cases.sh
          else
            ./run_medium_priority_tests.sh
          fi

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report-${{ matrix.test_type }}

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report-${{ matrix.test_type }}
          path: allure-report-${{ matrix.test_type }}
